name: Application CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U test_user"
          --health-interval=10s
          --health-timeout=3s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for PostgreSQL to be ready
        run: |
          for i in {1..10}; do
            if pg_isready -h localhost -p 5432 -U test_user; then
              echo "PostgreSQL is ready"
              break
            fi
            echo "Waiting for PostgreSQL..."
            sleep 5
          done

      - name: Create .env file
        run: |
          echo CLIENT_ADDRESS=\"localhost\" >> .env
          echo CLIENT_PORT=3000 >> .env
          echo ADMIN_USERNAME=\"Admin\" >> .env
          echo ADMIN_PASSWORD=\"Admin12345678\" >> .env
          echo JWT_SIGN_SECRET_KEY=\"e4aJWT8eSIGNbdb917TEST4tgj84SECRETwwff9kl2KEYd9c7a59fabc\" >> .env
          echo AUTH_TOKEN_EXPIRATION_MINUTES=15 >> .env
          echo DATABASE_URL=\"postgresql://test_user:test_password@localhost:5432/test_db\" >> .env
          echo GMAIL_ADDRESS=\"cool5admin@gmail.com\" >> .env
          echo TELEGRAM_BOT_TOKEN=\"test_token\" >> .env
          echo TELEGRAM_USER_NAME=\"\" >> .env
          echo TELEGRAM_USER_CHAT_ID=\"\" >> .env

      - name: Run linter
        run: pylint application/**/*.py --disable=C0301,C0114,C0115,C0116

      - name: Run tests
        run: pytest tests